name: Deploy
on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install execa
        run: npm install execa
      - name: Deploy app
        run: npm run deploy
