name: Update data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - run: |
          git config user.email "connorrothschild@gmail.com"
          git config user.name "connorrothschild"
          git add .
          git commit --allow-empty -m "Automatic data update"
          git push
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://mappingpoliceviolence.org/s/MPVDatasetDownload.xlsx
          downloaded_filename: public/data/raw.xlsx
          postprocess: ./postprocess.ts
      - name: Install execa
        run: npm install execa
      - name: Deploy app
        run: npm run deploy
